{{- if .Values.configurationFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-configuration
data:
{{- if .Values.mycnf.enable }}
  default-time-zone: {{ .Values.mycnf.defaulttimezone }}
  {{- if .Values.mycnf.generallog.enable }}
#  general_log: {{ .Values.mycnf.generallog.enable }}
  general_log_file: /var/lib/mysql/log/generallog.log
  {{- end }}
{{- else }}
{{- range $key, $val := .Values.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end }}
{{- end -}}