{{- if .Values.configurationFiles }}
{{- if .Values.mycnf.generallog.enable }}
  command: ["mkdir",{{ .Values.mycnf.generallog.path }}]
  command: ["chmod","777",{{ .Values.mycnf.generallog.path }}]
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-configuration
data:
{{- range $key, $val := .Values.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}