{{/* my.cnf は、必須とする。 */}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-configuration
data:
{{- if .Values.mycnf.enable }}
{{/* questions.yml を反映する場合 */}}
  my.cnf: |-
    [mysqld]
    default-time-zone={{ .Values.mycnf.defaulttimezone }}
    general_log_file=/var/lib/mysql/log/generallog.log
{{- else }}
{{/* values.yml を反映する場合 */}}
{{- range $key, $val := .Values.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
