# 2019.01.17 S.Harada 追加
# my.cnf を設定するか？
#{{- if .Values.mycnf.enable }}
#  {{ .Values.configurationFiles }} = true
#{{- end }}
# ここまで
{{- if .Values.configurationFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-configuration
data:
{{- range $key, $val := .Values.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
# 2019.01.17 S.Harada 追加
#  my.cnf を設定
#{{- if .Values.mycnf.enable }}
#  default-time-zone: "{{ .Values.mycnf.default-time-zone }}"
#  general_log: {{ .Values.mycnf.generallog.enable }}
#  {{- if .Values.mycnf.generallog.enable }}
#  general_log_file: "{{ .Values.mycnf.generallog.path }}{{ .Values.mycnf.generallog.file }}" 
  # フォルダの作成
#  command: ["mkdir",{{.Values.mycnf.generallog.path}}]
#  command: ["chmod","777",{{.Values.mycnf.generallog.path}}]
#  {{- end }}
#{{- end }}
# ここまで
{{- end -}}