{{- if .Values.configurationFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-configuration
data:
# questions.yaml を反映
{{- if .Values.mycnf.enable }}
#  default-time-zone: {{ }}
  general_log: {{ .Values.mycnf.generallog.enable }}
  general_log_file: /var/lib/mysql/log/generallog.log
{{- else }}
# values.yaml を反映
{{- range $key, $val := .Values.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end }}
{{- end -}}