apiVersion: v1
appVersion: 1.0.9
description: nfs-server-provisionerはKubernetes用のツリー外動的プロビジョニングプログラムです。 あなたはそれを使用して、ほとんどどこでも動作する共有ストレージを素早く簡単に展開することができます。
name: nfs-provisioner
icon: file://../nfs-logo.png
version: 0.1.0
# version: 0.2.1
maintainers:
- name: Shige Harada
  email: s-harada@truck-one.co.jp
home: https://github.com/kubernetes/charts/tree/master/stable/nfs-server-provisioner
sources:
- https://github.com/kubernetes-incubator/external-storage/tree/master/nfs
keywords:
- nfs
- storage
